databases:
  - name: stockpulse-ecommerce-db
    plan: free
    databaseName: ecommercedb
    user: ecommerce

services:
  - type: web
    name: stockpulse-ecommerce-api
    runtime: docker
    plan: free
    rootDir: ecommerce-backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/products
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: STOCKPULSE_API_URL
        value: https://stockpulse-api.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DB_HOST
        fromDatabase:
          name: stockpulse-ecommerce-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: stockpulse-ecommerce-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: stockpulse-ecommerce-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: stockpulse-ecommerce-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stockpulse-ecommerce-db
          property: password
